### ISSUE TITLE
riscv_isac coverage: Error: No such option: -v

### ISSUE THREAD

**Issue by weilinfox** [hushenwei2000/rvv-atg#17]
I am learning how to use this project and try to generate testcases with command ``python run.py -i vadd -t i`` and it failed with error below

```
$ python run.py -i vadd -t i

Tue, 07 Nov 2023 10:27:08 INFO     Creating output directory: 11-07-vadd-vlen128-vsew32-lmul1.0-masked
Tue, 07 Nov 2023 10:27:08 INFO     Finding CGF for: vadd in /home/hachi/sail/rvv-atg/cgfs/i/vadd.yaml.
Tue, 07 Nov 2023 10:27:08 INFO     lmul: 1.0.
vta, vma  False False
new_vtavma:  tu, mu
Tue, 07 Nov 2023 10:27:08 INFO     RVV-ATG: instr: vadd, vlen: 128, vsew: 32, lmul: 1.000000
Tue, 07 Nov 2023 10:27:08 INFO     Creating empty test for vadd
cp: '11-07-vadd-vlen128-vsew32-lmul1.0-masked/vadd_empty.S' and '11-07-vadd-vlen128-vsew32-lmul1.0-masked/vadd_empty.S' are the same file
Tue, 07 Nov 2023 10:27:08 INFO     Creating empty test for vadd: finish in 11-07-vadd-vlen128-vsew32-lmul1.0-masked/vadd_empty.S!
Tue, 07 Nov 2023 10:27:08 INFO     Running riscof coverage: vadd.empty
Tue, 07 Nov 2023 10:27:08 INFO     Running riscof coverage: vadd.empty, stage: Compiling...
riscv64-linux-gnu-gcc -march=rv64gv    -w     -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles                 -T /home/hachi/sail/rvv-atg/riscof_files/spike/env/link.ld                 -I /home/hachi/sail/rvv-atg/env/macros/vsew32_lmul1                 -I /home/hachi/sail/rvv-atg/env/p                 -I /home/hachi/sail/rvv-atg/env                 -I /home/hachi/sail/rvv-atg/env/spike                 -I /home/hachi/sail/rvv-atg/env/sail_cSim -mabi=lp64          vadd_empty.S -o ref_empty.elf -DTEST_CASE_1=True -DXLEN=64 -DFLEN=32;
Tue, 07 Nov 2023 10:27:08 INFO     Running riscof coverage: vadd.empty, stage: ObjDumping...
Tue, 07 Nov 2023 10:27:08 INFO     Running riscof coverage: vadd.empty, stage: Spike Running...
riscv_isac --verbose info coverage -d                         -t spike_vadd_empty.log --parser-name spike -o coverage_empty.rpt                         --sig-label begin_signature  end_signature                         --test-label rvtest_code_begin cleanup_epilogs                         -e ref_empty.elf -c /home/hachi/sail/rvv-atg/cgfs/dataset.yaml -c /home/hachi/sail/rvv-atg/cgfs/i/vadd.yaml -x64 -v128 --vsew 32 --lmul 1 --flen 32 -l vadd > isac_log_empty 2>&1;
Tue, 07 Nov 2023 10:27:08 INFO     Running riscof coverage: vadd.empty, stage: RISCV-ISAC Running...
Tue, 07 Nov 2023 10:27:08 INFO     Running riscof coverage vadd finish!
Tue, 07 Nov 2023 10:27:08 INFO     Creating first test for vadd
Traceback (most recent call last):
  File "/home/hachi/sail/rvv-atg/run.py", line 183, in <module>
    main()
  File "/home/hachi/sail/rvv-atg/run.py", line 170, in main
    run_integer(cwd, args, cgf,  output_dir)
  File "/home/hachi/sail/rvv-atg/run.py", line 106, in run_integer
    first_test = create_first_test(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/hachi/sail/rvv-atg/scripts/lib.py", line 118, in create_first_test
    return eval(func_str)
           ^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/home/hachi/sail/rvv-atg/scripts/create_test_integer/create_test_vadd.py", line 42, in create_first_test_vadd
    rs1_val, rs2_val = extract_operands(f, rpt_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hachi/sail/rvv-atg/scripts/test_common_info.py", line 193, in extract_operands
    f = open(rpt_path)
        ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/hachi/sail/rvv-atg/11-07-vadd-vlen128-vsew32-lmul1.0-masked/coverage_empty.rpt'
```

It seems that the ``riscv_isac`` command failed with error below

```
$ cat /home/hachi/sail/rvv-atg/11-07-vadd-vlen128-vsew32-lmul1.0-masked/isac_log_empty

    INFO | ****** RISC-V ISA Coverage 0.18.0 *******
    INFO | Copyright (c) 2020, InCore Semiconductors Pvt. Ltd.
    INFO | All Rights Reserved.
Usage: riscv_isac coverage [OPTIONS]
Try 'riscv_isac coverage --help' for help.

Error: No such option: -v
```

The riscv-isac is the latest version from https://github.com/riscv-software-src/riscv-isac . Thanks in advance.

**Comment by hushenwei2000** [comment]
Maybe you can refer to README, **my version** of riscv-isac  should be used. 

1. git clone https://github.com/hushenwei2000/riscv-isac-rvv
2. cd riscv-isac-rvv
3. git checkout vetcor !!!IMPORTANT!!!
4. pip install . --prefix=~/.local # Anywhere you want
5. Add ~/.local to your PATH

**Comment by weilinfox** [comment]
Sorry my bad. I will close this issue.

And I found that it depends on ``ruamel.yaml<0.18.0``
