### ISSUE TITLE
ERROR in generation of all tests (using generate_all.py code)

### ISSUE THREAD

**Issue by quswar-abid** [hushenwei2000/rvv-atg#2]
After setting up all that is required, I am getting following error:

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
Traceback (most recent call last):
  File "run.py", line 3, in <module>
  File "run.py", line 3, in <module>
        from ast import arg
from ast import arg
ImportErrorImportError: : cannot import name argcannot import name arg

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from ast import arg
ImportError: cannot import name arg
grep: 11-04-%s-vlen512-vsew32-lmul1.0/spike_%s_final.log: No such file or directory
cp: cannot stat '11-04-%s-vlen512-vsew32-lmul1.0/ref_final.elf': No such file or directory
```

A quick google lookup states something that points out a problem in calling out wrong imports (in multiple places) as in 

> The Python "ImportError: cannot import name" occurs when we have circular imports (importing members between the same files). To solve the error, move the objects to a third file and import them from a central location in other files, or nest one of the imports in a function.

**Comment by hushenwei2000** [comment]
`from ast import arg`, the `ast` is a lib of Python (seen https://python.readthedocs.io/en/stable/library/ast.html). I don't know which version is the minimum required. Maybe you can use Python 3.6 and higher.

**Comment by quswar-abid** [comment]
I am using Python 3.8 and the problem seems to be with the circular import.

**Comment by hushenwei2000** [comment]
`arg` is a lib package so I think this is a problem with the Python environment. Maybe try clearing the cache or something? The project works well on my server. So I ruled out the reason of coding error.

**Comment by quswar-abid** [comment]
Thanks, I'll try that, and close this issue later if fixed.

**Comment by quswar-abid** [comment]
You guessed right, the problem WAS with the python environment. I tried it on a different machine. I ran in to different problems though .. Consider following line though:

Line:     `riscof_dir = '/work/stu/swhu/projects/riscof-sample'`
Source: `https://github.com/hushenwei2000/rvv-atg/blob/master/run.py#L146`

It's a path according to your system I guess. Is it possible to set all paths from one, single location or evaluate at run time? This way any other can easily try this generator out!

Thanks, :)

**Comment by quswar-abid** [comment]
@hushenwei2000 can you confirm if the setup works on other systems? I can't figure out why I am not able to generate simple tests even without generate_all.py script. Running the following command gives me the error as shared below.

Command:
```
python3 run.py -t i -i vadd --vlen 512 --vsew 32 --lmul 1
```

Error:
```
xe-lpt-51@quswarabid:~/RIOS/rvv-atg(master)$ python3 run.py -t i -i vadd --vlen 512 --vsew 32 --lmul 1
Mon, 14 Nov 2022 12:02:39 INFO     Creating output directory: 11-14-vadd-vlen512-vsew32-lmul1.0
Mon, 14 Nov 2022 12:02:39 INFO     Finding CGF for: vadd in /home/xe-lpt-51/RIOS/rvv-atg/cgfs/i/vadd.yaml.
Mon, 14 Nov 2022 12:02:39 INFO     lmul: 1.0.
Mon, 14 Nov 2022 12:02:39 INFO     RVV-ATG: instr: vadd, vlen: 512, vsew: 32, lmul: 1.000000
Mon, 14 Nov 2022 12:02:39 INFO     Creating empty test for vadd
cp: '11-14-vadd-vlen512-vsew32-lmul1.0/vadd_empty.S' and '11-14-vadd-vlen512-vsew32-lmul1.0/vadd_empty.S' are the same file
Mon, 14 Nov 2022 12:02:39 INFO     Creating empty test for vadd: finish in 11-14-vadd-vlen512-vsew32-lmul1.0/vadd_empty.S!
Mon, 14 Nov 2022 12:02:39 INFO     Running riscof coverage: vadd.empty
Mon, 14 Nov 2022 12:02:39 INFO     Running riscof coverage: vadd.empty, stage: Compiling...
/home/xe-lpt-51/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gv    -w     -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles         -T /home/xe-lpt-51/RIOS/rvv-atg/env/p/link.ld         -I /home/xe-lpt-51/RIOS/rvv-atg/env/macros/vsew32_lmul1_nofail         -I /home/xe-lpt-51/RIOS/rvv-atg/env/p         -I /home/xe-lpt-51/RIOS/rvv-atg/env         -I /home/xe-lpt-51/RIOS/rvv-atg/env/sail_cSim -mabi=lp64  vadd_empty.S -o ref_empty.elf -DTEST_CASE_1=True -DXLEN=64 -DFLEN=32;
Mon, 14 Nov 2022 12:02:39 INFO     Running riscof coverage: vadd.empty, stage: ObjDumping...
Mon, 14 Nov 2022 12:02:39 INFO     Running riscof coverage: vadd.empty, stage: Spike Running...
riscv_isac --verbose info coverage -d                         -t spike_vadd_empty.log --parser-name spike -o coverage_empty.rpt                         --sig-label begin_signature  end_signature                         --test-label _start _end                         -e ref_empty.elf -c /home/xe-lpt-51/RIOS/rvv-atg/cgfs/dataset.yaml -c /home/xe-lpt-51/RIOS/rvv-atg/cgfs/i/vadd.yaml -x64 -v512 --vsew 32 --lmul 1 --flen 32 -l vadd > isac_log_empty 2>&1;
Mon, 14 Nov 2022 12:02:39 INFO     Running riscof coverage: vadd.empty, stage: RISCV-ISAC Running...
Mon, 14 Nov 2022 12:02:39 INFO     Running riscof coverage vadd finish!
Mon, 14 Nov 2022 12:02:39 INFO     Creating first test for vadd
Traceback (most recent call last):
  File "run.py", line 236, in <module>
    main()
  File "run.py", line 228, in main
    run_integer(cwd, args, cgf,  output_dir)
  File "run.py", line 111, in run_integer
    first_test = create_first_test(
  File "/home/xe-lpt-51/RIOS/rvv-atg/scripts/lib.py", line 114, in create_first_test
    return eval(func_str)
  File "<string>", line 1, in <module>
  File "/home/xe-lpt-51/RIOS/rvv-atg/scripts/create_test_integer/create_test_vadd.py", line 42, in create_first_test_vadd
    rs1_val, rs2_val = extract_operands(f, rpt_path)
  File "/home/xe-lpt-51/RIOS/rvv-atg/scripts/test_common_info.py", line 85, in extract_operands
    f = open(rpt_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/xe-lpt-51/RIOS/rvv-atg/11-14-vadd-vlen512-vsew32-lmul1.0/coverage_empty.rpt'
```

Is there a problem with coverage collection?

Can I skip this step?

**Comment by quswar-abid** [comment]
I guess I have fixed the installation. It's preferable to install through repo(s) instead of `pip install *` etc. The only thing I need to inquire as of now is (just to confirm that I have followed through and got what I needed) can you share some examples of created programs on any arbitrary configurations. Let's say `VLEN=1024, SEW=8, LMUL=1` etc. I'll compare then to be sure. Meanwhile, I think this issue better be closed.

Thanks,
Quswar Abid
